AWSTemplateFormatVersion: "2010-09-09"

Resources:

    TimestreamDatabase:
        Type: "AWS::Timestream::Database"
        Properties:
            DatabaseName: "macchinettafw"

    TimestreamTable:
        Type: "AWS::Timestream::Table"
        DependsOn: TimestreamDatabase        
        Properties:
            DatabaseName: "macchinettafw"
            TableName: "fw001"
            RetentionProperties: 
                MemoryStoreRetentionPeriodInHours: 12
                MagneticStoreRetentionPeriodInDays: 180
            MagneticStoreWriteProperties:
              EnableMagneticStoreWrites: true
              MagneticStoreRejectedDataLocation:
                S3Configuration:
                  BucketName: !Join ["", ["macchinettafw-", !Ref "AWS::AccountId", "-", !Ref "AWS::Region"]]  
                  EncryptionOption: "SSE_S3"
                  ObjectKeyPrefix: "timestream-table-macchinettafw-fw001-rejected"

Outputs:
  DatabaseName:
    Description: Timestream Database Name
    Value: !Ref TimestreamDatabase
  TableName:
    Description: Timestream Table Name
    Value: !GetAtt TimestreamTable.Name