{
 "title": "Macchinetta",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 4, "x": 0.6, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Vehicle Speed (kph)",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "\"macchinetta\"",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measure": "ActualVehicleSpeed",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BMSmaxPackTemperature\" or r[\"_field\"] == \"VCFRONT_tempAmbient\" or r[\"_field\"] == \"DIR_oilPumpFluidT\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "rawQuery": "SELECT * FROM $__database.$__table \nWHERE  measure_name = 'ActualVehicleSpeed'\n--      AND (time between ago(15m) and now())\n and time between from_iso8601_timestamp('${__from:date:iso}') and from_iso8601_timestamp('${__to:date:iso}')\nORDER BY time Desc Limit 1\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "\"fleet1\""
    }
   ]
  },
  {
   "title": "Battery Charge Level (%)",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "\"macchinetta\"",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measure": "Battery.BatteryChargeLevel",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BMSmaxPackTemperature\" or r[\"_field\"] == \"VCFRONT_tempAmbient\" or r[\"_field\"] == \"DIR_oilPumpFluidT\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "rawQuery": "SELECT * FROM $__database.$__table\nWHERE measure_name = 'Battery.BatteryChargeLevel'\n --     AND (time between ago(15m) and now())\n  and time between from_iso8601_timestamp('${__from:date:iso}') and from_iso8601_timestamp('${__to:date:iso}')\nORDER BY time Desc Limit 100\n\n\n\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "\"fleet1\""
    }
   ]
  },
  {
   "title": "Vehicle Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"macchinetta\"",
     "measure": "ActualVehicleSpeed",
     "rawQuery": "SELECT * FROM $__database.$__table\nWHERE measure_name = 'VehicleStatus'\n--      AND (time between ago(15m) and now())\n and time between from_iso8601_timestamp('${__from:date:iso}') and from_iso8601_timestamp('${__to:date:iso}')\nORDER BY time Desc Limit 1\n\n\n\n",
     "table": "\"fleet1\""
    }
   ]
  },
  {
   "title": "Led 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"macchinetta\"",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measure": "ActualVehicleSpeed",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TPMSFLpressure31F\" or r[\"_field\"] == \"TPMSFRpressure31F\" or r[\"_field\"] == \"TPMSRLpressure31F\" or r[\"_field\"] == \"TPMSRRpressure31F\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "rawQuery": "SELECT * FROM $__database.$__table\nWHERE measure_name = 'Led.Green'\n--    AND (time between ago(15m) and now())\n and time between from_iso8601_timestamp('${__from:date:iso}') and from_iso8601_timestamp('${__to:date:iso}')\nORDER BY time Desc Limit 1\n\n\n\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "\"fleet1\""
    }
   ]
  },
  {
   "title": "Led 2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"macchinetta\"",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measure": "Led.Red",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TPMSFLpressure31F\" or r[\"_field\"] == \"TPMSFRpressure31F\" or r[\"_field\"] == \"TPMSRLpressure31F\" or r[\"_field\"] == \"TPMSRRpressure31F\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "rawQuery": "SELECT * FROM $__database.$__table\nWHERE measure_name = 'Led.Red'\n--    AND (time between ago(15m) and now())\n and time between from_iso8601_timestamp('${__from:date:iso}') and from_iso8601_timestamp('${__to:date:iso}')\nORDER BY time Desc Limit 1\n\n\n\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "\"fleet1\""
    }
   ]
  },
  {
   "title": "Vehicle Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "database": "\"macchinetta\"",
     "measure": "ActualVehicleSpeed",
     "rawQuery": "SELECT * from $__database.$__table\nWHERE  measure_name = 'ActualVehicleSpeed'\n--      AND (time between ago(15m) and now())\n and time between from_iso8601_timestamp('${__from:date:iso}') and from_iso8601_timestamp('${__to:date:iso}')\nORDER BY time Desc Limit 100\n\n",
     "table": "\"fleet1\""
    }
   ]
  },
  {
   "title": "EV battery management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Battery Voltage (V)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 22 },
   "targets": [
    {
     "database": "\"macchinetta\"",
     "measure": "Battery.BatteryPackVoltage",
     "rawQuery": "SELECT * from $__database.$__table\nWHERE measure_name = 'Battery.BatteryPackVoltage'\n --     AND (time between ago(15m) and now())\n  and time between from_iso8601_timestamp('${__from:date:iso}') and from_iso8601_timestamp('${__to:date:iso}')\nORDER BY time Desc Limit 100\n",
     "table": "\"fleet1\""
    }
   ]
  },
  {
   "title": "Battery Charge Level (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 22 },
   "targets": [
    {
     "database": "\"macchinetta\"",
     "measure": "Battery.BatteryChargeLevel",
     "rawQuery": "SELECT * from $__database.$__table\nWHERE measure_name = 'Battery.BatteryChargeLevel'\n --     AND (time between ago(15m) and now())\n  and time between from_iso8601_timestamp('${__from:date:iso}') and from_iso8601_timestamp('${__to:date:iso}')\nORDER BY time Desc Limit 100\n\n",
     "table": "\"fleet1\""
    }
   ]
  }
 ]
}